
spring:
  application:
    name: oner365-springboot
    
  config:
    activate:
      on-profile: 
      - lt
      - zy
      - prod
      - dev

logging:
  config: classpath:logback-spring.xml